export enum RoleConversationType {
  SUPERADMIN_GHOTOK = "SUPERADMIN_GHOTOK",
  SUPERADMIN_ADMIN = "SUPERADMIN_ADMIN",
  SUPERADMIN_MODERATOR = "SUPERADMIN_MODERATOR",
  GHOTOK_ADMIN = "GHOTOK_ADMIN",
  GHOTOK_MODERATOR = "GHOTOK_MODERATOR",
}
